version: '3.9'
services:
  db:
    image: mysql:8.0.21
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE
